import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { imageConfigDefault } from "next/dist/shared/lib/image-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inicio",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header/>
        {children}</body>
    </html>
  );
}